spring:
  profiles:
    active: dev
    
---
server:
  port: 2333

spring:
  profiles: dev
  application:
    name: config-eureka-2333

eureka:
  instance:
    hostname: eureka2333.com
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://eureka2334.com:2334/eureka/, http://eureka2335.com:2335/eureka/

---
server:
  port: 2333

spring:
  profiles: test
  application:
    name: config-eureka-2333

eureka:
  instance:
    hostname: eureka2333.com
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://eureka2334.com:2334/eureka/, http://eureka2335.com:2335/eureka/
