spring:
  profiles: 
    active: dev

---
server:
  port: 80

spring:
  application:
    name: student-consumer-config-80
  profiles: dev   
  rabbitmq:
    host: 123.57.22.79
    port: 5672
    username: yibbit
    password: Yiang2Rabbit

eureka:
  client:
    service-url:
      defaultZone: http://eureka2333.com:2333/eureka, http://eureka2334.com:2334/eureka, http://eureka2335.com:2335/eureka
  instance:
    instance-id: student-consumer-config-80

---
server:
  port: 80

spring:
  application:
    name: student-consumer-config-80
  profiles: test   
  rabbitmq:
    host: 123.57.22.79
    port: 5672
    username: yibbit
    password: Yiang2Rabbit
    
eureka:
  client:
    service-url:
      defaultZone: http://eureka2333.com:2333/eureka, http://eureka2334.com:2334/eureka, http://eureka2335.com:2335/eureka
  instance:
    instance-id: student-consumer-config-80
