spring:
  profiles: 
    active: dev

---
server:
  port: 80

spring:
  application:
    name: student-consumer-config-80
  profiles: dev

eureka:
  client:
    service-url:
      defaultZone: http://eureka2333.com:2333/eureka, http://eureka2334.com:2334/eureka, http://eureka2335.com:2335/eureka
  instance:
    instance-id: student-consumer-config-80

---
server:
  port: 80

spring:
  application:
    name: student-consumer-config-80
  profiles: test

eureka:
  client:
    service-url:
      defaultZone: http://eureka2333.com:2333/eureka, http://eureka2334.com:2334/eureka, http://eureka2335.com:2335/eureka
  instance:
    instance-id: student-consumer-config-80