spring:
  profiles: 
    active: dev

---
server:
  port: 9999

spring:
  profiles: dev
  application:
    name: zuul-config-9999

eureka:
  client:
    service-url:
      defaultZone: http://eureka2333.com:2333/eureka, http://eureka2334.com:2334/eureka, http://eureka2335.com:2335/eureka
  instance:
    instance-id: zuul9999.com
    prefer-ip-address: true

---
server:
  port: 9999

spring:
  profiles: test
  application:
    name: zuul-config-9999

eureka:
  client:
    service-url:
      defaultZone: http://eureka2333.com:2333/eureka, http://eureka2334.com:2334/eureka, http://eureka2335.com:2335/eureka
  instance:
    instance-id: zuul9999.com
    prefer-ip-address: true