spring:
  profiles: 
    active: dev

---
server:
  port: 9999

spring:
  profiles: dev
  application:
    name: zuul-config-9999
  cloud:
    bus:
      enabled: true
      trace:
        enabled: true      
  rabbitmq:
    host: 123.57.22.79
    port: 5672
    username: yibbit
    password: Yiang2Rabbit

management:
  endpoints:
    web:
      exposure:
        include: 'refresh'

eureka:
  client:
    service-url:
      defaultZone: http://eureka2333.com:2333/eureka, http://eureka2334.com:2334/eureka, http://eureka2335.com:2335/eureka
  instance:
    instance-id: zuul9999.com
    prefer-ip-address: true

---
server:
  port: 9999

spring:
  profiles: test
  application:
    name: zuul-config-9999
  cloud:
    bus:
      enabled: true
      trace:
        enabled: true      
  rabbitmq:
    host: 123.57.22.79
    port: 5672
    username: yibbit
    password: Yiang2Rabbit
    
eureka:
  client:
    service-url:
      defaultZone: http://eureka2333.com:2333/eureka, http://eureka2334.com:2334/eureka, http://eureka2335.com:2335/eureka
  instance:
    instance-id: zuul9999.com
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: 'refresh'
        